### ISSUE TITLE
相册文件多选

### ISSUE THREAD

**Issue by HaooBin** [BugRui/CameraExtend#1]
请问可以实现相册文件的多选吗？

**Comment by BugRui** [comment]
有的，看文档

**Comment by HaooBin** [comment]
是的，我注意到了，万分感谢您在百忙抽空解答！




n
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BugRui/CameraExtend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 下午2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BugRui/CameraExtend] 相册文件多选 (Issue #1)





 
有的，看文档
